const Map<String, String> en = {
  'welcome': 'Welcome',
  'appTitle': 'GetX Multi Lingual Support',
  'title': 'Easy Language Translations',
  'subtitle':
      'This text will automatically be translated into the appropriate language',
  'button1': 'Switch language',
  'language': 'Language',
  'common': 'Common',
  'version': 'Version',
  'account': 'Account',
  'phoneNumber': 'Phone number',
  'email': 'Email',
  'signOut': 'Sign Out',
  'security': 'Security',
  'lockAppInBackground': 'Lock app in background',
  'useFingerprint': 'Use fingerprint',
  'allowApplicationToAccessStoredFingerprint':
      'Allow application to access stored fingerprint IDs.',
  'changePassword': 'Change password',
  'enableNotifications': 'Enable notifications',
  'misc': 'Misc',
  'policy': 'Policy',
  'username': 'Username',
  'map': 'Map',
  'setting': 'Setting',
};
