const Map<String, String> vi = {
  // TEXT
  'all': 'Tất cả',
  'ship': 'tàu',
  'car': 'xe',
  'running': 'Đang hoạt động',
  'run': 'Hoạt động',
  'pause': 'Dừng',
  'nosign': 'Mất kết nối',
  'noGPS': 'Mất GPS',
  'searching': 'Đang tìm kiếm...',
  'input-id': 'Nhập biển số cần tìm kiếm',
  'create': 'Tạo mới',
  'loading': 'Đang tải dữ liệu...',
  'update-successfully': 'Cập nhật dữ liệu thành công',
  'no-alter': 'Không có dữ liệu...',
  'no-internet': 'Mất kết nối internet..',
  'info': 'Thông tin',
  'location': 'Vị trí',
  'history': 'Xem lại',
  'no-device': 'Không có thiết bị',
  'no-sign-less': 'Mất LL',
  'addr': 'Địa chỉ',
  'day': 'ngày',
  'month': 'tháng',
  'year': 'năm',
  'hour': 'giờ',
  'minutes': 'phút',
  'seconds': 'giây',
  // AUTHENTICATION
  'username': 'Tên đăng nhập',
  'username-desc': 'Vui lòng nhập tên đăng nhập',
  'password': 'Mật khẩu',
  'password-desc': 'Nhập mật khẩu',
  'password-fogot': 'Quên mật khẩu',
  'password-change': 'Đổi mật khẩu',
  'signIn': 'Đăng nhập',
  'signOut': 'Đăng xuất',
  'signUp': 'Đăng ký',
  'account-none': 'Chưa có tài khoản',
  'phoneNumber': 'Số điện thoại',
  'email': 'Email',
  'account': 'Tài khoản',
  // MENU
  'home-map': 'Giám sát',
  'alter': 'Thông báo',
  'list': 'Danh sách',
  'report': 'Báo cáo',
  'setting': 'Cài đặt',
  // SETTING
  'common': 'Cơ bản',
  'language': 'Ngôn ngữ',
  'map': 'Bản đồ',
  'coordinates': 'Hệ tọa độ',
  'velocity': 'Đơn vị vận tốc',
  'vietnamese': 'Tiếng việt',
  'decimal': 'Tọa độ thập phân',
  'DM': 'Tọa độ phút',
  'DMS': 'Tọa độ giây',
  'nautical': 'Hải lý',
  'mile': 'Dặm',

  'security': 'Bảo mật',
  'lockAppInBackground': 'Khóa ứng dụng chạy nền',
  'useFingerprint': 'Chế độ vân tay',
  'allowApplicationToAccessStoredFingerprint':
      'Cho phép ứng dụng sử dụng mật khẩu vân tay',
  'enableNotifications': 'Bật thông báo',

  'misc': 'Khác',
  'policy': 'chính sách',
  'version': 'Phiên bản',
  // REPORT
  'rpHistory': 'Hành trình',
  'rpSpeed': 'Tốc độ',
  'rpDistance': 'Quãng đường',
  'rpOverMap': 'Quá phạm vi đánh bắt',
  'rpOverSpeed': 'BC quá tốc độ giới hạn',
  'rpOverRun': 'Thời gian lái xe liên tục',
  'rpPause': 'BC dừng đỗ',
  'rpTimeDriver': 'Thời gian lái xe của tài xế',
  'rpTotalByCar': 'BCTH xe',
  'rpTotalByShip': 'BCTH tàu',
  'rpTotalByDriver': 'BCTH tài xế',
  // INFO
  'device-info': 'Thông tin thiết bị',
  'device-edit': 'Sửa thiết bị',
  'device-name': 'Tên thiết bị',
  'device-type': 'Loại thiết bị',
  'status': 'Trạng thái',
  'ACC': 'ACC',
  'time-update': 'Thời gian cập nhật',
  'speed': 'Tốc độ',
  'latitude': 'Vĩ độ',
  'longitude': 'Kinh độ',
  'expiration': 'Ngày hết hạn',
  'vehical-number': 'Biển số',
  // INFO SHIP
  // INFO BOSS
};
