const Map<String, String> vi = {
  'welcome': 'Xin chào',
  'appTitle': 'GetX Đa ngôn ngữ',
  'title': 'GetX Đa ngôn ngữ',
  'subtitle': 'GetX Đa ngôn ngữ',
  'button1': 'GetX Đa ngôn ngữ',
  'language': 'Ngôn ngữ',
  'common': 'Cơ bản',
  'version': 'Phiên bản',
  'account': 'Tài khoản',
  'phoneNumber': 'Số điện thoại',
  'email': 'Email',
  'signOut': 'Đăng xuất',
  'security': 'Bảo mật',
  'lockAppInBackground': 'Khóa ứng dụng chạy nền',
  'useFingerprint': 'Chế độ vân tay',
  'allowApplicationToAccessStoredFingerprint':
      'Cho phép ứng dụng sử dụng mật khẩu vân tay',
  'changePassword': 'Đổi mật khẩu',
  'enableNotifications': 'Bật thông báo',
  'misc': 'Khác',
  'policy': 'chính sách',
  'username': 'Tên đăng nhập',
  'map': 'Bản đồ',
  'setting': 'Cài đặt',
};
